<?xml version="1.0" encoding="utf-8"?><Database Name="Biblioteca" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EVA\SQLEXPRESS;Initial Catalog=Biblioteca;User ID=MrEddy" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BibliotecaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Autores" Member="Autores">
    <Type Name="Autore">
      <Column Name="Autor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
</Database>